# Generated by Django 3.0 on 2019-12-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='Nombre_Estado',
            new_name='nombre_estado',
        ),
        migrations.AddField(
            model_name='flor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
