# Generated by Django 2.2.7 on 2019-12-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191208_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flor',
            name='id',
        ),
        migrations.AlterField(
            model_name='flor',
            name='nombre',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
