# Generated by Django 2.2.7 on 2019-12-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191217_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flor',
            name='idFlor',
        ),
        migrations.AlterField(
            model_name='flor',
            name='nombre',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
